services:
  ps1-0:
    build:
      context: .
      dockerfile: Dockerfile.1.0
    container_name: ps1-0

  ps1-1:
    build:
      context: .
      dockerfile: Dockerfile.1.1
    container_name: ps1-1

  ps1-2:
    build:
      context: .
      dockerfile: Dockerfile.1.2
    container_name: ps1-2
